services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8080"
    volumes:
      - ./dags:/usr/local/airflow/dags
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 5

  destination_dw_postgres:
    image: postgres:17rc1-alpine3.19
    restart: unless-stopped
    container_name: destination_dw_postgres
    env_file: ./.env
    ports:
      - "5439:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    depends_on:
      - webserver
    networks:
      - airflow_feegow

  apps_feegow:
    build:
      context: .
      dockerfile: Dockerfile_Feegow
    restart: unless-stopped
    container_name: apps_feegow
    env_file: ./.env
    volumes:
      - ./.dlt:/app/.dlt
      - ./src/prj_agenda/source_feegow_agenda.py:/app/source_feegow_agenda.py
      - ./pipeline_feegow_agenda.py:/app/pipeline_feegow_agenda.py
    depends_on:
      - destination_dw_postgres
    networks:
      - airflow_feegow

volumes:
  postgres-volume:

networks:
  airflow_feegow:
    driver: bridge