[sources.feegow_agenda]
feegow_token = "rnyutodksaç022876bxlsçs.açfpfjka"

[destination.postgres.credentials]
database = "prj_feegow_test"
username = "test"
password = "test"
host = "destination_dw_postgres"
port = 5432